version: "3.8"
services:
  api:
    build: "./api"
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  react-app:
    build: "./react-app"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
     - ./react-app:/home/node/app
     - /home/node/app/node_modules
    ports:
     - 8081:3000
